import { z } from 'zod';

export const Severity = z.enum(['critical', 'warning', 'info']);
export type Severity = z.infer<typeof Severity>;

export const Category = z.enum([
  'bug',
  'security',
  'perf',
  'api_misuse',
  'concurrency',
  'question',
]);
export type Category = z.infer<typeof Category>;

export const Finding = z.object({
  // Reject control characters in the path so a crafted finding cannot inject
  // markdown or break out of code spans when the finding is posted as a PR
  // review comment.
  file: z
    .string()
    .min(1)
    .regex(/^[^\r\n]+$/, { message: 'file must not contain line breaks' }),
  line: z.number().int().positive(),
  severity: Severity,
  category: Category,
  message: z.string().min(1),
  confidence: z.number().min(0).max(1),
  // An optional one-click fix. When the finding has an obvious, mechanical fix
  // for the single line it points at, this is the exact full replacement text
  // for that line, posted as a GitHub ```suggestion block. It is null when the
  // fix spans multiple lines, is unclear, or the model is not confident in the
  // exact replacement. Nullable rather than optional so the structured-output
  // schema stays strict (every field is required, this one may be null).
  suggestion: z.string().nullable(),
});
export type Finding = z.infer<typeof Finding>;

export const OverallAssessment = z.enum(['comment', 'request_changes', 'approve']);
export type OverallAssessment = z.infer<typeof OverallAssessment>;

// Output schema for the v0.3 verification gate. A second model audits each
// finding the base review produced and returns whether the diff confirms it is
// a real, worth-posting issue or a false positive. The gate drops a finding
// only when every verifier returns `false_positive`, and keeps it otherwise (a
// single `real`, a verifier error, or a split panel all keep the finding).
export const Verdict = z.object({
  verdict: z.enum(['real', 'false_positive']),
  reason: z.string().min(1),
});
export type Verdict = z.infer<typeof Verdict>;

export const MAX_FINDINGS_PER_REVIEW = 5;

export const ReviewOutput = z.object({
  summary: z.string().min(1),
  overall_assessment: OverallAssessment,
  findings: z.array(Finding).max(MAX_FINDINGS_PER_REVIEW),
});
export type ReviewOutput = z.infer<typeof ReviewOutput>;

export const MAX_WALKTHROUGH_ITEMS = 8;

// v0.2 PR walkthrough. A high-level map of the change for the reviewer, separate
// from the line-level findings. Generated by a dedicated call (see
// src/openai/walkthrough.ts) and rendered as a table at the top of the review
// body when WALKTHROUGH_ENABLED. Each item names an `area` (the file, module, or
// component touched) and a one-sentence `change`.
export const WalkthroughItem = z.object({
  area: z.string().min(1),
  change: z.string().min(1),
});
export type WalkthroughItem = z.infer<typeof WalkthroughItem>;

export const WalkthroughOutput = z.object({
  items: z.array(WalkthroughItem).max(MAX_WALKTHROUGH_ITEMS),
});
export type WalkthroughOutput = z.infer<typeof WalkthroughOutput>;
